//! Camera — pure ray generation from pixel coordinates.
//!
//! A Camera is pure data. `ray_direction` is a pure function: same pixel,
//! same direction, every time. No STORE, no JUMP.

use glam::Vec3;

/// Perspective camera described by origin and image plane corners.
///
/// Rays are generated by `ray_direction(u, v)` where `u, v ∈ [0, 1]`.
///
/// # Example
/// ```rust
/// use glam::Vec3;
/// use form_render::camera::Camera;
///
/// let cam = Camera::look_at(
///     Vec3::new(0.0, 0.0, -3.0),
///     Vec3::ZERO,
///     Vec3::Y,
///     60.0,
///     16.0 / 9.0,
/// );
/// let dir = cam.ray_direction(0.5, 0.5);
/// // Centre pixel should point roughly toward the target
/// assert!(dir.z > 0.0);
/// ```
#[derive(Debug, Clone, Copy)]
pub struct Camera {
    pub origin:     Vec3,
    pub lower_left: Vec3,
    pub horizontal: Vec3,
    pub vertical:   Vec3,
}

impl Camera {
    /// Construct a perspective camera from look-at parameters.
    ///
    /// # Arguments
    /// * `origin`       — camera position
    /// * `target`       — point the camera looks at
    /// * `up`           — world up vector (typically `Vec3::Y`)
    /// * `vfov_degrees` — vertical field of view in degrees
    /// * `aspect`       — width / height aspect ratio
    pub fn look_at(origin: Vec3, target: Vec3, up: Vec3, vfov_degrees: f32, aspect: f32) -> Self {
        let theta = vfov_degrees.to_radians();
        let half_h = (theta * 0.5).tan();
        let half_w = aspect * half_h;

        let w = (origin - target).normalize();
        let u = w.cross(up).normalize();
        let v = u.cross(w);

        let lower_left = origin - u * half_w - v * half_h - w;
        let horizontal = u * (2.0 * half_w);
        let vertical   = v * (2.0 * half_h);

        Camera { origin, lower_left, horizontal, vertical }
    }

    /// Generate a unit ray direction for normalised pixel coordinates.
    ///
    /// # Arguments
    /// * `u` — horizontal coordinate in [0, 1] (0 = left, 1 = right)
    /// * `v` — vertical coordinate in [0, 1] (0 = bottom, 1 = top)
    ///
    /// # Returns
    /// Unit direction vector for the ray through pixel `(u, v)`.
    pub fn ray_direction(&self, u: f32, v: f32) -> Vec3 {
        (self.lower_left + self.horizontal * u + self.vertical * v - self.origin).normalize()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn default_cam() -> Camera {
        Camera::look_at(
            Vec3::new(0.0, 0.0, -3.0),
            Vec3::ZERO,
            Vec3::Y,
            60.0,
            1.0,
        )
    }

    #[test]
    fn centre_ray_points_toward_target() {
        let dir = default_cam().ray_direction(0.5, 0.5);
        assert!(dir.z > 0.0, "centre ray should point +Z toward target");
    }

    #[test]
    fn ray_is_unit_length() {
        let cam = default_cam();
        for (u, v) in [(0.0, 0.0), (1.0, 0.0), (0.5, 0.5), (0.0, 1.0), (1.0, 1.0)] {
            let len = cam.ray_direction(u, v).length();
            assert!((len - 1.0).abs() < 1e-5, "u={u} v={v} len={len}");
        }
    }

    #[test]
    fn deterministic() {
        let cam = default_cam();
        let a = cam.ray_direction(0.3, 0.7);
        let b = cam.ray_direction(0.3, 0.7);
        assert_eq!(a, b);
    }

    #[test]
    fn left_and_right_rays_differ() {
        let cam = default_cam();
        let left  = cam.ray_direction(0.0, 0.5);
        let right = cam.ray_direction(1.0, 0.5);
        assert_ne!(left, right);
        assert!(left.x < right.x, "left ray should have smaller x component");
    }
}
